pack:
  runtime:
    enabled: false
  metadata:
    title: "Mecha Prototype"
    description: "mecha bullet hell prototype packed by histos"
  css:
    - "./style.css"
  scripts:
    - "./setup.js"
    - "./game.js"
